[package]
name = "datastorers"
version = "0.0.1"
authors = ["Andreas Pålsson <a.palsson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datastore_entity = { path = "datastore_entity" }
