[package]
name = "datastorers"
version = "0.0.1"
authors = ["Andreas Pålsson <a.palsson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-datastore1 = "*"
# This project intentionally uses an old version of Hyper. See
# https://github.com/Byron/google-apis-rs/issues/173 for more
# information.
hyper = "^0.10"
hyper-rustls = "^0.6"
yup-oauth2 = "^1.0"
datastore_entity = { path = "datastore_entity" }
