[package]
name = "datastore_entity_macro"
version = "0.0.1"
authors = ["Andreas Pålsson <a.palsson@gmail.com>", "Erik Zivkovic <erik@zivkovic.se>"]
edition = "2018"

[dependencies]
syn = "1.0"
quote = "1.0"

[lib]
proc-macro = true