name: Rust

on:
  push:
    branches: [ master ]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env: # Or as an environment variable
        TEST_PROJECT_NAME: ${{ secrets.TEST_PROJECT_NAME }}
      run: cargo test --verbose --features integration_tests
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::all
    - name: Run clippy for derives
      run: cd datastore_entity_derives && cargo clippy --all-targets --all-features -- -D warnings -D clippy::all
    - name: Run rustfmt check
      run: cargo fmt -- --check
    - name: Run rustfmt check for derives
      run: cd datastore_entity_derives && cargo fmt -- --check
